from networks.get_dag_asia import get_dag_asia
from networks.get_dag_galaxy import get_dag_galaxy
from networks.get_dag_inversetree import get_dag_inversetree
from networks.get_dag_rain import get_dag_rain
from networks.network_generator import Network
